"""Interview session endpoints.

- POST /interview/sessions       → create a new interview session
- GET  /interview/sessions/{id}  → get session status & results
- WS   /interview/ws/{id}        → real-time audio interview via WebSocket
"""

from __future__ import annotations

import json
import logging
import uuid
from base64 import b64encode
from typing import TYPE_CHECKING

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from app.core.config import settings
from app.schemas.interview import (
    InterviewSession,
    Question,
    SessionState,
    WSMessageType,
)

if TYPE_CHECKING:
    from app.services.interview_session import SessionOrchestrator
    from app.services.llm_service import LLMService
    from app.services.stt_service import STTService
    from app.services.tts_service import TTSService
    from app.services.vad_service import VADService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/interview", tags=["interview"])

# In-memory session store (swap for DB/Redis in prod)
_sessions: dict[str, SessionOrchestrator] = {}


def _build_services() -> tuple[VADService, STTService, TTSService, LLMService]:
    """Instantiate all AI services from app settings."""
    from app.services.llm_service import LLMConfig, LLMService
    from app.services.stt_service import STTConfig, STTService
    from app.services.tts_service import TTSConfig, TTSService
    from app.services.vad_service import VADConfig, VADService

    vad = VADService(VADConfig(
        threshold=settings.vad_threshold,
        min_silence_duration_ms=settings.vad_min_silence_ms,
        min_speech_duration_ms=settings.vad_min_speech_ms,
    ))
    stt = STTService(STTConfig(
        model_name=settings.whisper_model,
        language=settings.whisper_language,
    ))
    tts = TTSService(TTSConfig(
        sample_rate=settings.tts_sample_rate,
        chunk_size=settings.tts_chunk_size,
    ))
    llm = LLMService(LLMConfig(
        base_url=settings.ollama_base_url,
        model=settings.ollama_model,
        temperature=settings.ollama_temperature,
    ))
    return vad, stt, tts, llm


@router.post("/sessions")
async def create_session(job_id: str, candidate_id: str) -> dict:
    """Create a new interview session for a candidate.

    TODO: Load real questions from DB (generated by HrFlow pipeline).
    For now uses placeholder questions.
    """
    from app.services.interview_session import SessionOrchestrator

    session_id = str(uuid.uuid4())

    # Placeholder — replace with DB lookup of pre-generated questions
    questions = [
        Question(id=str(i), text=f"Question technique #{i+1}", topic="general", difficulty="medium")
        for i in range(20)
    ]

    session = InterviewSession(
        session_id=session_id,
        job_id=job_id,
        candidate_id=candidate_id,
        questions=questions,
    )

    vad, stt, tts, llm = _build_services()
    await vad.load_model()
    await tts.load_model()

    orchestrator = SessionOrchestrator(
        session=session,
        vad=vad,
        stt=stt,
        tts=tts,
        llm=llm,
        job_context=f"Job ID: {job_id}",
    )

    _sessions[session_id] = orchestrator

    return {
        "session_id": session_id,
        "state": session.state.value,
        "total_questions": len(questions),
        "ws_url": f"/interview/ws/{session_id}",
    }


@router.get("/sessions/{session_id}")
async def get_session(session_id: str) -> dict:
    """Get current session state, progress, and results."""
    orchestrator = _sessions.get(session_id)
    if orchestrator is None:
        return {"error": "Session not found"}

    session = orchestrator.session
    return {
        "session_id": session.session_id,
        "state": session.state.value,
        "current_question_index": session.current_question_index,
        "total_questions": len(session.questions),
        "answers_count": len(session.answers),
        "answers": [
            {
                "question_id": a.question_id,
                "transcript": a.transcript,
                "evaluation": a.llm_evaluation,
                "follow_up_asked": a.follow_up_asked,
            }
            for a in session.answers
        ],
    }


async def _send_json(ws: WebSocket, msg_type: WSMessageType, data: dict) -> None:
    """Send a JSON control message over WebSocket."""
    await ws.send_json({"type": msg_type.value, **data})


async def _send_audio(ws: WebSocket, audio: bytes) -> None:
    """Send audio data as base64 JSON message over WebSocket."""
    await ws.send_json({
        "type": WSMessageType.AUDIO_CHUNK.value,
        "audio": b64encode(audio).decode("ascii"),
        "format": "pcm_s16le",
        "sample_rate": settings.tts_sample_rate,
    })


@router.websocket("/ws/{session_id}")
async def interview_websocket(websocket: WebSocket, session_id: str) -> None:
    """Bidirectional audio WebSocket for the interview."""
    orchestrator = _sessions.get(session_id)
    if orchestrator is None:
        await websocket.close(code=4004, reason="Session not found")
        return

    await websocket.accept()
    logger.info("WebSocket connected for session %s", session_id)

    try:
        # Start interview: send intro + first question
        event = await orchestrator.start()
        await _send_json(websocket, WSMessageType.STATE_CHANGE, {
            "state": event.new_state.value,
        })
        if event.question_text:
            await _send_json(websocket, WSMessageType.QUESTION_TEXT, {
                "text": event.question_text,
            })
        if event.audio:
            await _send_audio(websocket, event.audio)

        # Signal client: ready to receive audio
        await _send_json(websocket, WSMessageType.STATE_CHANGE, {
            "state": SessionState.LISTENING.value,
        })

        # Main loop: receive audio chunks, process pipeline
        while orchestrator.session.state != SessionState.DONE:
            data = await websocket.receive_bytes()

            event = await orchestrator.handle_audio_chunk(data)
            if event is None:
                continue

            await _send_json(websocket, WSMessageType.STATE_CHANGE, {
                "state": event.new_state.value,
            })

            if event.transcript:
                await _send_json(websocket, WSMessageType.TRANSCRIPT, {
                    "text": event.transcript,
                })

            if event.evaluation:
                await _send_json(websocket, WSMessageType.STATE_CHANGE, {
                    "state": event.new_state.value,
                    "evaluation": event.evaluation,
                })

            if event.question_text:
                await _send_json(websocket, WSMessageType.QUESTION_TEXT, {
                    "text": event.question_text,
                })

            if event.audio:
                await _send_audio(websocket, event.audio)

            if event.new_state == SessionState.ASKING:
                await _send_json(websocket, WSMessageType.STATE_CHANGE, {
                    "state": SessionState.LISTENING.value,
                })

        # Interview complete
        await _send_json(websocket, WSMessageType.STATE_CHANGE, {
            "state": SessionState.DONE.value,
            "total_answers": len(orchestrator.session.answers),
        })
        await websocket.close()

    except WebSocketDisconnect:
        logger.info("WebSocket disconnected for session %s", session_id)
    except Exception:
        logger.exception("Error in interview WebSocket for session %s", session_id)
        await _send_json(websocket, WSMessageType.ERROR, {
            "message": "Internal server error",
        })
        await websocket.close(code=1011)
